In [9]:
import numpy as np
x1 = np.linspace(0,.5, 6)
x2 = np.linspace(0.51,.6, 10)
x3 = np.linspace(0.7,1, 4)
np.hstack((x1,x2,x3))

array([0.  , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.7 , 0.8 , 0.9 , 1.  ])

In [12]:
def magnitud(x):
    y = pow((np.sum(np.power(x,2))),0.5)
    return  y


3.7416573867739413


In [13]:
def normalizar(x):
    y = pow((np.sum(np.power(x,2))),0.5)
    return  x/y

print(normalizar([1,2,3]))

[0.26726124 0.53452248 0.80178373]


In [20]:
x = np.linspace(-2,2,9)
y = x < 0
z = x >1 0
np.hstack((x[y]*-1,x[z]))


array([2. , 1.5, 1. , 0.5, 0. , 0.5, 1. , 1.5, 2. ])

In [45]:
def h(x):
    a = x < 0
    b = (x >= 0) & (x <= 1)
    c = x > 1
    return (np.hstack((x[a],x[b],x[c])))

x = np.array([0.1,-2,0.5,5])

print(h(x))

[-2.   0.1  0.5  5. ]


In [54]:
x = np.linspace(-8,10,9)
condiciones = [x<0,  (x>=0) & (x<1),  (x>=1) & (x<2), x>=2]
resultados =  [-x,    x**3,          x**2,         4]

np.select(condiciones,resultados) 

array([8.  , 5.75, 3.5 , 1.25, 1.  , 4.  , 4.  , 4.  , 4.  ])

In [72]:
x = np.linspace(-8,15,10)

np.piecewise(x, [(x<0), (x>=0)&(x<1), (x>=1)&(x<2), (x>=2)], [lambda x: -x, lambda x: x**3, lambda x: x**2, 4])


array([8.        , 5.44444444, 2.88888889, 0.33333333, 4.        ,
       4.        , 4.        , 4.        , 4.        , 4.        ])

## Proyección Vectorial ##
---
La proyección vectorial nos permite proyectar un vector u sobre la dirección de un vector v.  El ejemplo visto en clase de una proyección es imaginar si los rayos del sol producen una sombra del vector u sobre el piso que sería el vector y

Para ello, desde el extremo de u, trazamos una recta perpendicular al vector v: Ahora, sobre el vector v, dibujamos un vector desde el origen de ambos vectores hasta el punto donde se cortan la recta perpendicular y el vector v.

#Definir una función para cálculo en NumPy#

### Definir una función para cálculo en NumPy ###
---
Se me ocurre una función en NumPy que devuelve el riesgo de un cliente basado en su Score Crediticio.  Esto se podría usar para saber el riesgo crediticio de una cartera de clientes

### Producto Cruz ###
En matemáticas, el producto vectorial de Gibbs o producto cruz es una operación binaria entre dos vectores en un espacio tridimensional. El resultado es un vector perpendicular a los vectores que se multiplican, y por lo tanto normal al plano que los contiene

